name: Copy Docker Compose
description: Copy the Docker Compose file to a VPS using SSH.

inputs:
    project:
        description: Name of the project.
        required: true

    host:
        description: VPS host address.
        required: true

    key:
        description: SSH private key for authentication.
        required: true

    port:
        description: SSH port for connection.
        required: false
        default: 22

    username:
        description: SSH username for login.
        required: true

runs:
    using: composite
    steps:
        - uses: appleboy/scp-action@v1
          with:
              key: ${{ inputs.key }}
              host: ${{ inputs.host }}
              port: ${{ inputs.port }}
              username: ${{ inputs.username }}

              source: ./compose.yml
              target: /home/${{ inputs.username }}/apps/${{ inputs.project }}
