name: CI

on:
    pull_request:
        branches: [master]
        types: [opened, reopened, synchronize, ready_for_review]

concurrency:
    group: ci-${{ github.ref }}
    cancel-in-progress: true

env:
    NEXT_TELEMETRY_DISABLED: 1
    TURBO_TELEMETRY_DISABLED: 1
    TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}

jobs:
    commitlint:
        if: ${{ github.event.pull_request.draft == false }}
        runs-on: ubuntu-latest
        steps:
            - name: Set up code
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: Set up environment
              uses: ./.github/actions/ci-setup

            - name: Run commitlint
              run: |
                  pnpm exec commitlint \
                  --from=${{ github.event.pull_request.base.sha }} \
                  --to=${{ github.event.pull_request.head.sha }}

    format:
        needs: commitlint
        runs-on: ubuntu-latest
        steps:
            - name: Set up code
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: Set up environment
              uses: ./.github/actions/ci-setup

            - name: Run formatter
              run: pnpm turbo fmt:check --affected

    lint:
        needs: commitlint
        runs-on: ubuntu-latest
        steps:
            - name: Set up code
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: Set up environment
              uses: ./.github/actions/ci-setup

            - name: Run linter
              run: pnpm turbo lint:check --affected

    test:
        needs: commitlint
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Set up code
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: Set up environment
              uses: ./.github/actions/ci-setup

            - name: Set up playwright
              run: pnpm --filter web exec playwright install chromium --with-deps

            - name: Run tests
              run: pnpm turbo test:check --affected

    build:
        needs: [lint, test]
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Checkout code
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: Set up environment
              uses: ./.github/actions/ci-setup

            - name: Restore Next.js cache
              uses: ./.github/actions/nextjs-cache

            - name: Build affected packages
              run: pnpm turbo build --affected
